# vim: ts=4:sts=4:sw=4
#
# @author <lucile.gaultier@oceandatalab.com>
# @date 2024-01-10
#
# Copyright (C) 2024 OceanDataLab

"""
Metadata dictionnary for saving L3 outputs
"""

COMPLEVEL = 4
ZLIB = True
FV32 = 1.e+20
ENC_FV = {'zlib': ZLIB, 'complevel': COMPLEVEL, '_FillValue': FV32,
          'dtype': 'float32'}
ENC = {'zlib': ZLIB, 'complevel': COMPLEVEL}

COORDINATES = {'along_track': {'dtype': 'int64',
                               'long_name': 'Along track distance from start',
                               'units': 'km'},
            'cross_track': {'dtype': 'int32',
                            'long_name': 'Across track distance from nadir',
                            'units': 'km'},
            'sample_time':{'dtype': 'int64',
                           'long_name':  'Time of WaCM overpass',
                           'units': 'seconds since 1970-01-01',
                           'comments': 'Time of WaCM overpass in seconds since 1970',
                           'standard_name': 'time',
                           'calendar': 'proleptic_gregorian'},

            'lat': {'dtype': 'float32', 'valid_min': -90., 'valid_max': 90,
                    'long_name': 'latitude', 'standard_name': 'latitude',
                    'units': 'degrees_north'},
            'lon': {'dtype': 'float32', 'valid_min': -180., 'valid_max': 180,
                    'long_name': 'longitude', 'standard_name': 'longitude',
                    'units': 'degrees_east'},
            'number_of_pass': {'dtype': 'int32', 'valid_min': 0., 'valid_max': 1000000,
                    'long_name': 'total number of passes since start', 'standard_name': 'number_of_pass',
                    'units': ''}
               }

GEOMETRY = {'swath_blanking': {
                               'comment': "Flagged in areas of the swath that are expected to have unacceptable error performance.",
                               },
           'encoder_aft': {'dtype': 'float32', 'valid_min': -180,
                           'valid_max': 180., 'units': 'degrees',
                           'long_name': 'encoder_aft',
                           'comments': 'Angle counter-clockwise from the bearing of the satellite for the aft look',
                           },
           'encoder_fore': {'dtype': 'float32', 'valid_min': -180,
                           'valid_max': 180., 'units': 'degrees',
                           'long_name': 'encoder_fore',
                           'comments': 'Angle counter-clockwise from the bearing of the satellite for the fore look',
                           },
           'azimuth_aft': {'dtype': 'float32', 'valid_min': -180,
                           'valid_max': 180., 'units': 'degrees',
                           'long_name': 'azimuth_aft',
                           'comments': 'Angle counter-clockwise from the North for the aft look',
                           },
           'azimuth_fore': {'dtype': 'float32', 'valid_min': -180,
                           'valid_max': 180., 'units': 'degrees',
                           'long_name': 'azimuth_fore',
                           'comments': 'Angle counter-clockwise from the North for the fore look',
                           },
           'radial_angle_aft': {'dtype': 'float32', 'valid_min': -180,
                           'valid_max': 360., 'units': 'degrees',
                           'long_name': 'radial_angle_aft',
                           'comments': 'Angle clockwise from the North for the aft look',
                           },
           'radial_angle_fore': {'dtype': 'float32', 'valid_min': -180,
                           'valid_max': 360., 'units': 'degrees',
                           'long_name': 'radial_angle_fore',
                           'comments': 'Angle counter-clockwise from the North for the fore look',
                           },
           'bearing': {'dtype': 'float32', 'valid_min': -180,
                           'valid_max': 180., 'units': 'degrees',
                           'long_name': 'bearing',
                           'comments': 'Direction of travel of the satellite platform',
                           },
           }

VARIABLES = { 'u_model': {'dtype': 'float32', 'valid_min': -100, 'valid_max': 100,
                          'units': 'm/s',
                          'long_name': 'Eastward velocity from model',
                           },
            'v_model': {'dtype': 'float32', 'valid_min': -100, 'valid_max': 100,
                        'units': 'm/s',
                        'long_name': 'Northward velocity from model',
                        },
           'ur_nonoise_aft': {'dtype': 'float32', 'valid_min': -100, 'valid_max': 100,
                              'units': 'm/s',
                              'long_name': 'Radial velocity without noise for the aft look',
                              },
           'ur_nonoise_fore': {'dtype': 'float32', 'valid_min': -100, 'valid_max': 100,
                               'units': 'm/s',
                               'long_name': 'Radial velocity without noise for the fore look',
                               },
           'ur_aft': {'dtype': 'float32', 'valid_min': -100, 'valid_max': 100,
                               'units': 'm/s',
                               'long_name': 'Radial velocity for the aft look',
                               },
           'ur_fore': {'dtype': 'float32', 'valid_min': -100, 'valid_max': 100,
                                'units': 'm/s',
                                'long_name': 'Radial velocity for the fore look',
                                },
           'wind_speed':   {'dtype': 'float32', 'valid_min': -100, 'valid_max': 100,
                            'units': 'm/s',
                            'long_name': 'Wind velocity norm',
                            },
           'wind_direction': {'dtype': 'float32', 'valid_min': -180, 'valid_max': 360,
                              'units': 'degrees',
                              'long_name': 'Wind velocity direction',
                              },
           'u_al_model': {'dtype': 'float32', 'valid_min': -100, 'valid_max': 100,
                          'units': 'm/s',
                          'long_name': 'velocity from model in the along track direction',
                          },
           'u_ac_model': {'dtype': 'float32', 'valid_min': -100, 'valid_max': 100,
                          'units': 'm/s',
                          'long_name': 'velocity from model in the across track direction',
                          },
           'ur_al': {'dtype': 'float32', 'valid_min': -100, 'valid_max': 100,
                     'units': 'm/s',
                     'long_name': 'velocity reconstructed from radials in the along track direction',
                      },
           'ur_ac': {'dtype': 'float32', 'valid_min': -100, 'valid_max': 100,
                     'units': 'm/s',
                     'long_name': 'velocity reconstructed from radials in the across track direction',
                      },
           'ur_nonoise_al': {'dtype': 'float32', 'valid_min': -100, 'valid_max': 100,
                             'units': 'm/s',
                             'long_name': 'velocity reconstructed from radials without noise in the along track direction',
                             },
           'ur_nonoise_ac': {'dtype': 'float32', 'valid_min': -100, 'valid_max': 100,
                             'units': 'm/s',
                             'long_name': 'velocity reconstructed from radials without noise in the across track direction',
                             },
           'ur_eastward': {'dtype': 'float32', 'valid_min': -100, 'valid_max': 100,
                           'units': 'm/s',
                           'long_name': 'Eastward velocity reconstructed from radials',
                           },
           'ur_northward': {'dtype': 'float32', 'valid_min': -100, 'valid_max': 100,
                            'units': 'm/s',
                            'long_name': 'Northward velocity reconstructed from radials',
                            },
           'ur_nonoise_eastward': {'dtype': 'float32', 'valid_min': -100, 'valid_max': 100,
                                   'units': 'm/s',
                                   'long_name': 'Eastward velocity reconstructed from radials without noise',
                                   },
           'ur_nonoise_northward': {'dtype': 'float32', 'valid_min': -100, 'valid_max': 100,
                                    'units': 'm/s',
                                    'long_name': 'Northward velocity reconstructed from radials without noise',
                                    },
             }
